import React, { useEffect } from 'react';
import { ArrowLeft, Shield, FileText } from 'lucide-react';

interface TermsPageProps {
  onBack: () => void;
}

const TermsPage: React.FC<TermsPageProps> = ({ onBack }) => {
  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);

  return (
    <div className="min-h-screen bg-cyber-black text-gray-300 font-sans selection:bg-cyber-cyan selection:text-black relative">
      <div className="fixed inset-0 z-0 pointer-events-none">
         <div className="absolute inset-0 cyber-grid opacity-20"></div>
      </div>

      <div className="relative z-10 max-w-4xl mx-auto px-6 py-12 md:py-24">
        
        {/* Header */}
        <button onClick={onBack} className="flex items-center gap-2 text-gray-500 hover:text-cyber-cyan transition-colors mb-8 font-mono text-xs uppercase tracking-widest">
           <ArrowLeft className="w-4 h-4" /> Return to Terminal
        </button>

        <div className="border-b border-gray-800 pb-12 mb-12">
           <div className="flex items-center gap-4 mb-4">
              <div className="w-12 h-12 bg-gray-900 rounded-lg flex items-center justify-center border border-gray-800">
                 <FileText className="w-6 h-6 text-gray-400" />
              </div>
              <h1 className="text-4xl md:text-5xl font-black text-white tracking-tighter">TERMS OF SERVICE</h1>
           </div>
           <p className="text-gray-500 font-mono text-sm">Last Updated: October 24, 2025</p>
        </div>

        {/* Content */}
        <div className="space-y-12 text-sm leading-relaxed text-gray-400">
           
           <section>
              <h3 className="text-lg font-bold text-white mb-4 uppercase tracking-wide flex items-center gap-2">
                 <div className="w-1.5 h-1.5 bg-cyber-cyan rounded-full"></div> 1. Acceptance of Terms
              </h3>
              <p>
                 By accessing or using SignalixAI ("the Platform"), you agree to be bound by these Terms of Service. If you do not agree to all of these terms, do not use the Platform. We reserve the right to update these terms at any time.
              </p>
           </section>

           <section>
              <h3 className="text-lg font-bold text-white mb-4 uppercase tracking-wide flex items-center gap-2">
                 <div className="w-1.5 h-1.5 bg-cyber-cyan rounded-full"></div> 2. Service Description
              </h3>
              <p>
                 SignalixAI is a technical analysis tool that uses artificial intelligence to interpret market data. The insights provided are generated by algorithms and should not be considered as financial advice, investment recommendations, or an offer to sell or buy any assets.
              </p>
           </section>

           <section>
              <h3 className="text-lg font-bold text-white mb-4 uppercase tracking-wide flex items-center gap-2">
                 <div className="w-1.5 h-1.5 bg-cyber-cyan rounded-full"></div> 3. No Financial Advice
              </h3>
              <div className="p-6 bg-red-900/10 border border-red-900/30 rounded-lg">
                 <p className="text-red-300 font-medium">
                    SignalixAI is not a registered investment advisor, broker, or dealer. You agree that SignalixAI is not responsible for any trading decisions you make based on data or "verdicts" presented on the platform. All trading involves risk.
                 </p>
              </div>
           </section>

           <section>
              <h3 className="text-lg font-bold text-white mb-4 uppercase tracking-wide flex items-center gap-2">
                 <div className="w-1.5 h-1.5 bg-cyber-cyan rounded-full"></div> 4. User Conduct
              </h3>
              <p className="mb-4">You agree not to:</p>
              <ul className="list-disc pl-5 space-y-2">
                 <li>Use the platform for any illegal purpose.</li>
                 <li>Attempt to reverse engineer the AI models or API.</li>
                 <li>Share your account credentials with third parties.</li>
                 <li>Automate scraping of SignalixAI data without express written permission.</li>
              </ul>
           </section>

           <section>
              <h3 className="text-lg font-bold text-white mb-4 uppercase tracking-wide flex items-center gap-2">
                 <div className="w-1.5 h-1.5 bg-cyber-cyan rounded-full"></div> 5. Subscription & Payments
              </h3>
              <p>
                 Pro subscriptions are billed on a recurring basis. You may cancel your subscription at any time via the dashboard. Refunds are not provided for partial billing periods unless required by law. We use secure third-party payment processors (Polar) and do not store your credit card details.
              </p>
           </section>

           <section>
              <h3 className="text-lg font-bold text-white mb-4 uppercase tracking-wide flex items-center gap-2">
                 <div className="w-1.5 h-1.5 bg-cyber-cyan rounded-full"></div> 6. Limitation of Liability
              </h3>
              <p>
                 IN NO EVENT SHALL SIGNALIX_AI BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL OR PUNITIVE DAMAGES, OR ANY LOSS OF PROFITS OR REVENUES, WHETHER INCURRED DIRECTLY OR INDIRECTLY, OR ANY LOSS OF DATA, USE, GOODWILL, OR OTHER INTANGIBLE LOSSES.
              </p>
           </section>

           <div className="pt-12 border-t border-gray-800 text-center">
              <p className="text-xs text-gray-600 font-mono">
                 Questions? Contact contact@realanima.online
              </p>
           </div>

        </div>
      </div>
    </div>
  );
};

export default TermsPage;